name: Cache Maven Build Output

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Cache Build Output
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-build-${{ hashFiles('**/*') }}
        restore-keys: |
          ${{ runner.os }}-build-
    - name: Build with Maven
      run: mvn -B package --file pom.xml
