name: Cache Java Tool

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cache Java
      uses: actions/cache@v2
      with:
        path: ~/.sdkman/candidates/java
        key: ${{ runner.os }}-java-${{ hashFiles('**/sdkmanrc') }}
        restore-keys: |
          ${{ runner.os }}-java-
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - run: java -version
